language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_COMPONENTS_VERSION=2.3.*
  - SYMFONY_COMPONENTS_VERSION=2.4.*

cache:
  directories:
    - $COMPOSER_CACHE_DIR


before_script:
    - composer require --prefer-source --dev symfony/http-kernel:${SYMFONY_COMPONENTS_VERSION}
    - composer require --prefer-source --dev symfony/console:${SYMFONY_COMPONENTS_VERSION}
    - composer require --prefer-source --dev symfony/config:${SYMFONY_COMPONENTS_VERSION}
    - composer require --prefer-source --dev symfony/dependency-injection:${SYMFONY_COMPONENTS_VERSION}
    - composer install

script:
    - bin/atoum

    - composer create-project --no-interaction symfony/framework-standard-edition:${SYMFONY_COMPONENTS_VERSION} Tests/Functionals
    - rm -rf Tests/Functionals/composer.lock Tests/Functionals/vendor
    - Tests/bin/functionals ${TRAVIS_BRANCH}
    - composer --working-dir=Tests/Functionals install
    - Tests/Functionals/bin/console
