language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_COMPONENTS_VERSION=~2.3.6
  - SYMFONY_COMPONENTS_VERSION=2.4.*
  - SYMFONY_COMPONENTS_VERSION=2.5.*

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
    - composer require --no-update --prefer-source symfony/http-kernel:${SYMFONY_COMPONENTS_VERSION}
    - composer require --no-update --prefer-source symfony/console:${SYMFONY_COMPONENTS_VERSION}
    - composer require --no-update --prefer-source symfony/config:${SYMFONY_COMPONENTS_VERSION}
    - composer require --no-update --prefer-source symfony/dependency-injection:${SYMFONY_COMPONENTS_VERSION}
    - composer install

script:
    - bin/atoum

    - composer create-project --no-install --no-interaction --prefer-source symfony/framework-standard-edition:${SYMFONY_COMPONENTS_VERSION} Tests/Functionals
    - Tests/bin/functionals ${TRAVIS_BRANCH}
    - composer --working-dir=Tests/Functionals install --prefer-source
    - Tests/Functionals/bin/console --ansi
